# Generated by Django 5.2.17 on 2026-08-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('abarrotes_ferreteria', 'Abarrotes / Ferretería'), ('restaurante', 'Restaurante'), ('clinica', 'Clínica'), ('nexos', 'Nexos Estratégicos'), ('personalizada', 'Personalizada')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('identificador_externo', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['empresa', 'nombre'],
            },
        ),
    ]
