# Generated by Django 5.2.17 on 2026-08-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_catalogo_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('carrito', 'Carrito'), ('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('pagado', 'Pagado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='carrito', max_length=20)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_telefono', models.CharField(blank=True, max_length=50)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('direccion_entrega', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('identificador_externo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='core.canal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('importe', models.DecimalField(decimal_places=4, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_pedido', to='core.producto')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='uniq_pedido_empresa_numero'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='pedido_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0)), name='pedido_descuento_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='pedido_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='pedido_detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='pedido_detalle_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0)), name='pedido_detalle_descuento_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='pedido_detalle_importe_no_negativo'),
        ),
    ]
