# Generated by Django 5.2.17 on 2026-08-12 11:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_pedidodetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('tipo', models.CharField(choices=[('abarrotes', 'Abarrotes / Ferretería'), ('restaurante', 'Restaurante'), ('clinica', 'Clínica'), ('nexos', 'Nexos Estratégicos'), ('personalizada', 'Personalizada')], max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('retirada', 'Retirada')], default='borrador', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla maestra',
                'verbose_name_plural': 'Plantillas maestras',
                'ordering': ['tipo', 'nombre', '-version'],
                'indexes': [models.Index(fields=['tipo', 'estado', 'activa'], name='idx_pm_tipo_estado_activa')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='uniq_plantilla_maestra_slug_version')],
            },
        ),
        migrations.CreateModel(
            name='InstalacionPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_instalada', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprovisionando', 'Aprovisionando'), ('lista', 'Lista'), ('error', 'Error'), ('suspendida', 'Suspendida')], default='pendiente', max_length=20)),
                ('clave_idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ultimo_error', models.TextField(blank=True)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones_plantilla', to='core.empresa')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones_plantilla', to='core.licencia')),
                ('plantilla', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalacion_maestra', to='core.plantilla')),
                ('plantilla_maestra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='core.plantillamaestra')),
            ],
            options={
                'verbose_name': 'Instalación de plantilla',
                'verbose_name_plural': 'Instalaciones de plantillas',
                'ordering': ['-iniciada_en'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='idx_inst_empresa_estado')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'plantilla_maestra'), name='uniq_instalacion_empresa_pm')],
            },
        ),
        migrations.CreateModel(
            name='PlantillaVariableMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Sí / No'), ('fecha', 'Fecha'), ('hora', 'Hora'), ('json', 'JSON')], default='texto', max_length=20)),
                ('valor_default', models.TextField(blank=True)),
                ('requerida', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('plantilla_maestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.plantillamaestra')),
            ],
            options={
                'verbose_name': 'Variable maestra',
                'verbose_name_plural': 'Variables maestras',
                'ordering': ['plantilla_maestra', 'orden', 'clave'],
                'constraints': [models.UniqueConstraint(fields=('plantilla_maestra', 'clave'), name='uniq_pm_variable_clave')],
            },
        ),
    ]
