# Generated by Django 5.2.17 on 2026-08-12 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plantillamaestra_instalacionplantilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='core.plantilla'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogos', to='core.plantilla'),
        ),
    ]
