# Generated by Django 5.2.17 on 2026-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_plantilla_tipo_alter_plantillamaestra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillamaestra',
            name='identificador_externo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
