# Generated by Django 5.2.17 on 2026-08-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_plantillamaestra_identificador_externo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='canal',
            constraint=models.UniqueConstraint(fields=('bot', 'tipo'), name='uniq_canal_bot_tipo'),
        ),
    ]
