# Generated by Django 5.2.17 on 2026-08-18 19:03

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_unique_canal_bot_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, max_length=500, upload_to=core.models.ruta_imagen_principal_producto, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validar_tamano_imagen_producto]),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=500, upload_to=core.models.ruta_imagen_galeria_producto, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validar_tamano_imagen_producto])),
                ('texto_alternativo', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['producto', 'orden'], name='idx_prodimg_producto_orden')],
            },
        ),
    ]
