# Generated by Django 5.2.17 on 2026-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_producto_imagen_principal_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='domicilio_calle',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='empresa',
            name='domicilio_ciudad',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='empresa',
            name='domicilio_codigo_postal',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='empresa',
            name='domicilio_colonia',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='empresa',
            name='domicilio_estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='domicilio_municipio',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='empresa',
            name='domicilio_numero_exterior',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='domicilio_numero_interior',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='domicilio_pais',
            field=models.CharField(default='México', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='giro_negocio',
            field=models.CharField(default='', max_length=150),
        ),
    ]
