# Generated by Django 5.2.17 on 2026-08-19 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_empresa_datos_segmentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitada', models.BooleanField(default=False)),
                ('modo', models.CharField(choices=[('pruebas', 'Pruebas'), ('produccion', 'Producción')], default='pruebas', max_length=20)),
                ('estado_conexion', models.CharField(choices=[('desconectada', 'Desconectada'), ('conectada', 'Conectada'), ('error', 'Error')], default='desconectada', max_length=20)),
                ('mp_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('access_token_cifrado', models.TextField(blank=True, default='')),
                ('refresh_token_cifrado', models.TextField(blank=True, default='')),
                ('token_expira_en', models.DateTimeField(blank=True, null=True)),
                ('conectado_en', models.DateTimeField(blank=True, null=True)),
                ('ultima_validacion_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_mercadopago', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuración Mercado Pago',
                'verbose_name_plural': 'Configuraciones Mercado Pago',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('mercadopago', 'Mercado Pago')], default='mercadopago', max_length=30)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado'), ('contracargo', 'Contracargo'), ('expirado', 'Expirado'), ('error', 'Error')], default='creado', max_length=20)),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('preference_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('merchant_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=1200)),
                ('estado_proveedor', models.CharField(blank=True, default='', max_length=50)),
                ('detalle_estado_proveedor', models.CharField(blank=True, default='', max_length=150)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('ultima_notificacion_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['proveedor', 'estado'], name='core_pago_prov_est_idx'), models.Index(fields=['pedido', 'estado'], name='core_pago_ped_est_idx')],
            },
        ),
    ]
