# Generated by Django 5.2.17 on 2026-08-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mercado_pago_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_palabras', models.PositiveIntegerField(default=1000)),
                ('palabras_consumidas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('agotada', 'Agotada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('activada_en', models.DateTimeField(auto_now_add=True)),
                ('agotada_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas_ia', to='core.empresa')),
            ],
            options={
                'ordering': ['-activada_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=30)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('habilitada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('inactiva', 'Inactiva'), ('activa', 'Activa'), ('pausada_agotada', 'Pausada por bolsa agotada'), ('error', 'Error')], default='inactiva', max_length=30)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('ultima_actividad_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_ia', to='core.empresa')),
            ],
            options={
                'ordering': ['empresa_id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(default='openai', max_length=30)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('palabras_salida', models.PositiveIntegerField()),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_salida', models.PositiveIntegerField(default=0)),
                ('referencia_conversacion', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('origen', models.CharField(blank=True, default='', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='core.bolsaia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_ia', to='core.empresa')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bolsaia',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('empresa',), name='core_bolsaia_activa_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bolsaia',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_palabras__gt', 0)), name='core_bolsaia_cantidad_ck'),
        ),
        migrations.AddConstraint(
            model_name='bolsaia',
            constraint=models.CheckConstraint(condition=models.Q(('palabras_consumidas__lte', models.F('cantidad_palabras'))), name='core_bolsaia_consumo_ck'),
        ),
        migrations.AddIndex(
            model_name='consumoia',
            index=models.Index(fields=['empresa', 'creado_en'], name='core_consumoia_emp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='consumoia',
            index=models.Index(fields=['bolsa', 'creado_en'], name='core_consumoia_bol_fecha_idx'),
        ),
    ]
