# Generated by Django 5.2.17 on 2026-08-19 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ia_bolsa_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGoogleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_conexion', models.CharField(choices=[('desconectada', 'Desconectada'), ('conectada', 'Conectada'), ('error', 'Error')], db_index=True, default='desconectada', max_length=20)),
                ('habilitada', models.BooleanField(default=False)),
                ('cuenta_email', models.EmailField(blank=True, default='', max_length=254)),
                ('calendar_id', models.CharField(blank=True, default='', max_length=512)),
                ('calendar_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('zona_horaria', models.CharField(default='America/Mexico_City', max_length=64)),
                ('access_token_cifrado', models.TextField(blank=True, default='')),
                ('refresh_token_cifrado', models.TextField(blank=True, default='')),
                ('token_expira_en', models.DateTimeField(blank=True, null=True)),
                ('scopes_concedidos', models.TextField(blank=True, default='')),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('conectado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_google_calendar', to='core.empresa')),
            ],
            options={
                'ordering': ('empresa_id',),
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente_confirmacion', 'Pendiente de confirmación'), ('programada', 'Programada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('error', 'Error')], db_index=True, default='pendiente_confirmacion', max_length=32)),
                ('origen', models.CharField(choices=[('chatbot', 'Chatbot'), ('admin', 'Administración'), ('api', 'API')], default='chatbot', max_length=20)),
                ('nombre_cliente', models.CharField(blank=True, default='', max_length=200)),
                ('telefono_cliente', models.CharField(blank=True, default='', max_length=50)),
                ('email_cliente', models.EmailField(blank=True, default='', max_length=254)),
                ('servicio', models.CharField(blank=True, default='', max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('zona_horaria', models.CharField(default='America/Mexico_City', max_length=64)),
                ('google_calendar_id', models.CharField(blank=True, default='', max_length=512)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=512)),
                ('google_event_etag', models.CharField(blank=True, default='', max_length=512)),
                ('google_html_link', models.URLField(blank=True, default='', max_length=1000)),
                ('referencia_conversacion', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('google_sincronizada_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='core.bot')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.empresa')),
            ],
            options={
                'ordering': ('-inicio', '-id'),
                'indexes': [models.Index(fields=['empresa', 'inicio'], name='core_cita_emp_inicio_idx'), models.Index(fields=['empresa', 'estado', 'inicio'], name='core_cita_emp_est_ini_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='core_cita_fin_gt_inicio'), models.UniqueConstraint(condition=models.Q(('google_event_id', ''), _negated=True), fields=('empresa', 'google_event_id'), name='core_cita_google_event_uniq')],
            },
        ),
    ]
