# Generated by Django 5.2.17 on 2026-08-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bot_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='tipo',
            field=models.CharField(choices=[('abarrotes', 'Abarrotes'), ('ferreteria', 'Ferretería'), ('farmacia', 'Farmacia'), ('restaurante', 'Restaurante'), ('clinica', 'Clínica'), ('estetica', 'Estética'), ('administrativa', 'Administrativa'), ('nexos', 'Nexos Estratégicos'), ('personalizada', 'Personalizada'), ('abarrotes_ferreteria', 'Abarrotes / Ferretería (legado)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plantillamaestra',
            name='tipo',
            field=models.CharField(choices=[('abarrotes', 'Abarrotes'), ('ferreteria', 'Ferretería'), ('farmacia', 'Farmacia'), ('restaurante', 'Restaurante'), ('clinica', 'Clínica'), ('estetica', 'Estética'), ('administrativa', 'Administrativa'), ('nexos', 'Nexos Estratégicos'), ('personalizada', 'Personalizada')], max_length=50),
        ),
    ]
