# Generated by Django 5.2.17 on 2026-08-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_bot_faq'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='uniq_producto_catalogo_sku',
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
