# Generated by Django 5.2.17 on 2026-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_producto_sku_opcional_repetible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='importe_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cita',
            name='importe_pago_requerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cita',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cita',
            name='pago_confirmado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='politica_pago_aplicada',
            field=models.CharField(choices=[('sin_pago', 'No requiere pago'), ('anticipo', 'Requiere anticipo'), ('pago_completo', 'Requiere pago completo')], default='sin_pago', max_length=30),
        ),
        migrations.AddField(
            model_name='cita',
            name='porcentaje_pago_requerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cita',
            name='retencion_pago_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionagenda',
            name='politica_pago_cita',
            field=models.CharField(choices=[('sin_pago', 'No requiere pago'), ('anticipo', 'Requiere anticipo'), ('pago_completo', 'Requiere pago completo')], default='sin_pago', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracionagenda',
            name='porcentaje_anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionagenda',
            name='retencion_pago_minutos',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
