# Generated by Django 5.2.17 on 2026-08-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_agenda_pago_citas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_servicio', to='core.producto'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.cita'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.pedido'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cita', 'estado'], name='core_pago_cita_est_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pedido__isnull', False), ('cita__isnull', True)), models.Q(('pedido__isnull', True), ('cita__isnull', False)), _connector='OR'), name='core_pago_destino_xor'),
        ),
    ]
