# Generated by Django 5.2.17 on 2026-08-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_pago_cita_servicio_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='moneda',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
