# Generated by Django 5.2.17 on 2026-08-30 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cita_moneda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
                'ordering': ['orden', 'nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_envio_fijo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('envio_gratis_desde', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tiempo_estimado_minutos', models.PositiveIntegerField(default=30)),
                ('habilitada', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de restaurante',
                'verbose_name_plural': 'Configuraciones de restaurante',
            },
        ),
        migrations.CreateModel(
            name='GrupoModificadorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('modificador', 'Modificador'), ('extra', 'Extra')], default='modificador', max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
                ('minimo', models.PositiveSmallIntegerField(default=0)),
                ('maximo', models.PositiveSmallIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo modificador',
                'verbose_name_plural': 'Grupos modificadores',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcionModificadorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio_adicional', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opción de modificador',
                'verbose_name_plural': 'Opciones de modificador',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoEstadoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('carrito', 'Carrito'), ('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('pagado', 'Pagado'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('en_camino', 'En camino'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notificacion_whatsapp_enviada', models.BooleanField(default=False)),
                ('notificacion_whatsapp_intentada_en', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('notificacion_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Evento de estado de pedido',
                'verbose_name_plural': 'Eventos de estado de pedido',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_extras',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_modificadores',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_productos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_estimado_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_orden',
            field=models.CharField(blank=True, choices=[('comedor', 'Comedor'), ('para_llevar', 'Para llevar'), ('domicilio', 'A domicilio')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='extras_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='modificadores_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_extras',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_modificadores',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('pagado', 'Pagado'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('en_camino', 'En camino'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='carrito', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_productos__gte', 0)), name='pedido_subprod_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_modificadores__gte', 0)), name='pedido_submod_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_extras__gte', 0)), name='pedido_subextra_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('costo_envio__gte', 0)), name='pedido_envio_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_base__isnull', True), ('precio_base__gte', 0), _connector='OR'), name='ped_det_precio_base_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_modificadores__gte', 0)), name='ped_det_mod_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_extras__gte', 0)), name='ped_det_extra_no_neg'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.catalogo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='configuracionrestaurante',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_restaurante', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='grupomodificadorproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_modificadores', to='core.producto'),
        ),
        migrations.AddField(
            model_name='opcionmodificadorproducto',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.grupomodificadorproducto'),
        ),
        migrations.AddField(
            model_name='pedidoestadoevento',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_eventos', to='core.pedido'),
        ),
        migrations.AddField(
            model_name='pedidoestadoevento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_estado_pedido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='categoriaproducto',
            index=models.Index(fields=['catalogo', 'activa', 'orden'], name='idx_catprod_cat_act_ord'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproducto',
            constraint=models.UniqueConstraint(fields=('catalogo', 'nombre'), name='uniq_categoria_catalogo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='configuracionrestaurante',
            constraint=models.CheckConstraint(condition=models.Q(('costo_envio_fijo__gte', 0)), name='rest_costo_envio_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='configuracionrestaurante',
            constraint=models.CheckConstraint(condition=models.Q(('envio_gratis_desde__isnull', True), ('envio_gratis_desde__gte', 0), _connector='OR'), name='rest_envio_gratis_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='configuracionrestaurante',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_estimado_minutos__gt', 0)), name='rest_tiempo_estimado_pos'),
        ),
        migrations.AddIndex(
            model_name='grupomodificadorproducto',
            index=models.Index(fields=['producto', 'activo', 'orden'], name='idx_grupomod_prod_act_ord'),
        ),
        migrations.AddConstraint(
            model_name='grupomodificadorproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='uniq_grupo_mod_prod_nombre'),
        ),
        migrations.AddConstraint(
            model_name='grupomodificadorproducto',
            constraint=models.CheckConstraint(condition=models.Q(('maximo__gte', models.F('minimo'))), name='grupo_mod_min_le_max'),
        ),
        migrations.AddConstraint(
            model_name='grupomodificadorproducto',
            constraint=models.CheckConstraint(condition=models.Q(('maximo__gte', 1)), name='grupo_mod_max_pos'),
        ),
        migrations.AddConstraint(
            model_name='grupomodificadorproducto',
            constraint=models.CheckConstraint(condition=models.Q(('obligatorio', False), ('minimo__gte', 1), _connector='OR'), name='grupo_mod_oblig_min'),
        ),
        migrations.AddIndex(
            model_name='opcionmodificadorproducto',
            index=models.Index(fields=['grupo', 'activa', 'orden'], name='idx_opmod_grup_act_ord'),
        ),
        migrations.AddConstraint(
            model_name='opcionmodificadorproducto',
            constraint=models.UniqueConstraint(fields=('grupo', 'nombre'), name='uniq_opcion_grupo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='opcionmodificadorproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_adicional__gte', 0)), name='opcion_mod_precio_no_neg'),
        ),
        migrations.AddIndex(
            model_name='pedidoestadoevento',
            index=models.Index(fields=['pedido', 'fecha'], name='idx_pedestado_ped_fecha'),
        ),
        migrations.AddIndex(
            model_name='pedidoestadoevento',
            index=models.Index(fields=['pedido', 'estado_nuevo'], name='idx_pedestado_ped_estado'),
        ),
    ]
