# Generated by Django 5.2.17 on 2026-09-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_restaurante_modelo_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPromocionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_estrella', models.BooleanField(default=False)),
                ('texto_promocional', models.TextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_promocion_ia', to='core.empresa')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promocion_ia', to='core.producto')),
            ],
            options={
                'verbose_name': 'Promoción IA de producto',
                'verbose_name_plural': 'Promociones IA de productos',
                'ordering': ['empresa_id', 'producto_id'],
                'indexes': [models.Index(fields=['empresa', 'activa', 'es_estrella'], name='idx_promia_emp_act_est')],
            },
        ),
        migrations.CreateModel(
            name='ReglaVentaCruzadaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_promocional', models.TextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_venta_cruzada_ia', to='core.empresa')),
                ('producto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_cross_sell_origen', to='core.producto')),
                ('producto_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_cross_sell_recomendado', to='core.producto')),
            ],
            options={
                'verbose_name': 'Regla de venta cruzada IA',
                'verbose_name_plural': 'Reglas de venta cruzada IA',
                'ordering': ['empresa_id', 'prioridad', 'id'],
                'indexes': [models.Index(fields=['empresa', 'producto_origen', 'activa', 'prioridad'], name='idx_crossia_emp_ori_act')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'producto_origen', 'producto_recomendado'), name='uniq_crossia_emp_ori_rec')],
            },
        ),
    ]
