# Generated by Django 5.2.17 on 2026-09-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_producto_promocion_ia_venta_cruzada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='proveedor',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('negocio', 'Efectivo / contra entrega')], default='mercadopago', max_length=30),
        ),
    ]
