"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# TNL-SECRETS-ENV-V1
# En el servidor se lee del archivo; en CI llega por variable de entorno.
SECRET_KEY_FILE = Path(
    "/opt/tunegociolisto/configs/django-secrets/secret_key"
)
SECRET_KEY = (
    os.environ.get("DJANGO_SECRET_KEY")
    or SECRET_KEY_FILE.read_text().strip()
)

# SECURITY WARNING: don't run with debug turned on in production!
# TNL-DEBUG-ENV-V1
# Apagado por defecto; solo se enciende con DJANGO_DEBUG=1 (desarrollo local).
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "api.negociolisto.com.mx", "admin.negociolisto.com.mx"]

CSRF_TRUSTED_ORIGINS = [
    "https://admin.negociolisto.com.mx",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    "core.middleware.ClientLifecycleMiddleware", # TNL-CLIENT-LIFECYCLE-SETTINGS-V1
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

ADMIN_DB_PASSWORD_FILE = Path(
    "/opt/tunegociolisto/infrastructure/secrets/admin_db_password"
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DJANGO_DB_NAME", "tnl_admin_db"),
        "USER": os.environ.get("DJANGO_DB_USER", "tnl_admin_app"),
        "PASSWORD": (
            os.environ.get("DJANGO_DB_PASSWORD")
            or ADMIN_DB_PASSWORD_FILE.read_text().strip()
        ),
        "HOST": os.environ.get("DJANGO_DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DJANGO_DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# TNL-STATIC-ROOT-PRODUCTION-V1
STATIC_ROOT = BASE_DIR.parent.parent / "staticfiles"

# TNL-PRODUCT-MEDIA-V1
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(
    os.environ.get("DJANGO_MEDIA_ROOT", "/opt/tunegociolisto/media")
)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# NegocioListo Administration
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# TNL-PUBLIC-MEDIA-URL-V1
NEGOCIOLISTO_PUBLIC_MEDIA_BASE_URL = (
    "https://admin.negociolisto.com.mx"
)

# ============================================================
# TNL-MEDIA-PERMISSIONS-V1
# Los archivos multimedia deben ser legibles por Nginx.
# ============================================================

FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# ============================================================
# TNL-LOGGING-CONSOLE-V1
# Con DEBUG=False, el handler "console" por defecto de Django deja
# de escribir. Este handler mantiene los logs de Django (INFO y
# superiores, incluidos errores 500 con traceback) en stderr,
# que gunicorn envía a journald. Sin archivos ni correos.
# ============================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
