services:
  redis:
    image: redis:7.4-bookworm
    container_name: tnl-redis
    restart: unless-stopped

    env_file:
      - /opt/tunegociolisto/infrastructure/env/redis.env

    command:
      - redis-server
      - --aclfile
      - /run/secrets/redis_users_acl
      - --dir
      - /data
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec

    secrets:
      - redis_users_acl
      - redis_password

    volumes:
      - /opt/tunegociolisto/infrastructure/volumes/redis:/data

    networks:
      - backend

    ports:
      - "127.0.0.1:6379:6379"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "REDISCLI_AUTH=$$(cat /run/secrets/redis_password) redis-cli ping | grep -qx PONG"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    stop_grace_period: 30s

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"

secrets:
  redis_users_acl:
    file: /opt/tunegociolisto/infrastructure/secrets/redis-users.acl

  redis_password:
    file: /opt/tunegociolisto/infrastructure/secrets/redis_password

networks:
  backend:
    external: true
    name: tunegociolisto-backend
